<a href="https://colab.research.google.com/github/LuisPalominoR/Prueba1/blob/main/Clase_2_B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://i.imgur.com/6U6q5jQ.png"/>

<a target="_blank" href="https://colab.research.google.com/github/PythonVersusR/basicDataStructures_vectors/blob/main/R_Python_Vectors.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Vectors in R and Python

In [1]:
## if needed, run this and RESTART KERNEL
# import os
# os.environ['R_HOME'] ='/Library/Frameworks/R.framework/Resources'

In [2]:
%load_ext rpy2.ipython

## 1. Creating

In [3]:
import numpy as np

namesP=np.array(["Qing", "Françoise", "Raúl", "Bjork","Marie"])
agesP=np.array([32,33,28,30,29])
countryP=np.array(["China", "Senegal", "España", "Norway","Korea"])
educationP=np.array(["Bach", "Bach", "Master", "PhD","PhD"])

In [4]:
namesP

array(['Qing', 'Françoise', 'Raúl', 'Bjork', 'Marie'], dtype='<U9')

In [5]:
%%R
namesR=c("Qing", "Françoise", "Raúl", "Bjork","Marie")
agesR=c(32,33,28,30,29)
countryR=c("China", "Senegal", "España", "Norway","Korea")
educationR=c("Bach", "Bach", "Master", "PhD","PhD")

In [6]:
%%R
namesR

[1] "Qing"      "Françoise" "Raúl"      "Bjork"     "Marie"    


## 2. Accessing

In [7]:
# Keep in mind the positions in Python start in **0**.
agesP[0]

32

In [8]:
%%R
agesR[1]

[1] 32


In [9]:
#last element
countryP[-1]

'Korea'

In [10]:
%%R
tail(countryR,1)

[1] "Korea"


### Slices

In [11]:
# several, using slices:
agesP[1:4] #second to fourth

array([33, 28, 30])

In [12]:
%%R
agesR[2:4]

[1] 33 28 30


In [13]:
# non consecutive

agesP[[0,2,3]]

array([32, 28, 30])

In [14]:
%%R
agesR[c(1,3,4)]

[1] 32 28 30


## Replacing

### by Position

In [15]:
countryP[2]="Spain"

# list changed:
countryP

array(['China', 'Senegal', 'Spain', 'Norway', 'Korea'], dtype='<U7')

In [16]:
%%R
countryR[3]="Spain"

# list changed:
countryR

[1] "China"   "Senegal" "Spain"   "Norway"  "Korea"  


### By Value

In [17]:
countryP=np.char.replace(countryP, 'China', 'PR China')
countryP

array(['PR China', 'Senegal', 'Spain', 'Norway', 'Korea'], dtype='<U8')

In [18]:
%%R
countryR[countryR=='China']="PR China"
countryR

[1] "PR China" "Senegal"  "Spain"    "Norway"   "Korea"   


## Deleting

### By Position

In [19]:
countryP=np.delete(countryP,-1)
countryP

array(['PR China', 'Senegal', 'Spain', 'Norway'], dtype='<U8')

In [20]:
%%R
countryR=countryR[-length(countryR)]
countryR

[1] "PR China" "Senegal"  "Spain"    "Norway"  


In [21]:
# for several positions

vectorP=np.array([1,2,3,4,5,6])
vectorP=np.delete(vectorP,range(1,4))
#now:
vectorP

array([1, 5, 6])

In [22]:
%%R

vectorR=c(1,2,3,4,5,6)
vectorR=vectorR[-c(2:4)]

#now:
vectorR

[1] 1 5 6


In [23]:
# non consecutive
byeIndex=[1, 3, 5]

vectorP=np.array([11,22,33,44,55,66])
new_vectorP=np.delete(vectorP,byeIndex)

#now:
new_vectorP

array([11, 33, 55])

In [24]:
%%R
vectorR=c(11,22,33,44,55,66)
new_vectorR=vectorR[-c(2,4,6)]
new_vectorR

[1] 11 33 55


### by Value

In [25]:
# by value
vectorP=np.array([1,3,45,3,3])

vectorP=np.delete(vectorP, np.where(vectorP == 3))

#  changed:
vectorP

array([ 1, 45])

In [26]:
%%R

vectorR=c(1,3,45,3,3)
vectorR=vectorR[vectorR!=3]
vectorR


[1]  1 45


In [27]:
# by value
vectorP=np.array([1,3,45,3,3])

#vectorP=
vectorP=np.delete(vectorP, np.isin(vectorP,[1,45]))

#  changed:
vectorP

array([3, 3, 3])

In [28]:
%%R

vectorR=c(1,3,45,3,3)
vectorR=vectorR[!vectorR%in%c(1,45)]
vectorR

[1] 3 3 3


## Inserting values

### at the End

In [29]:
vectorP=np.array([1,2,3,4])
vectorP=np.append(vectorP,5)
vectorP

array([1, 2, 3, 4, 5])

In [30]:
%%R
vectorR=c(1,2,3,4)
vectorR=c(vectorR,5)
vectorR

[1] 1 2 3 4 5


### in a particular location

In [31]:
vectorP=np.array([1,2,3,4])
vectorP=np.insert(vectorP,obj=1,values=10) #obj is position
vectorP

array([ 1, 10,  2,  3,  4])

In [32]:
%%R
vectorR=c(1,2,3,4)
vectorR=append(vectorR,10,after=1)
vectorR

[1]  1 10  2  3  4


## Concatenating

In [33]:
import numpy as np

vectorP1=np.array([1,2,3,4])
vectorP2=np.array(['a','b'])
vectorP12=np.concatenate((vectorP1,vectorP2))
vectorP12

array(['1', '2', '3', '4', 'a', 'b'], dtype='<U21')

In [34]:
%%R
vectorR1=c(1,2,3,4)
vectorR2=c('a','b')
vectorR12=c(vectorR1,vectorR2)
vectorR12

[1] "1" "2" "3" "4" "a" "b"


Remember that vectors support just one data type, and coercion will activate when different data types are detected.

In [35]:
vectorP1=np.array([1,2,3,4,"O"])
vectorP1

array(['1', '2', '3', '4', 'O'], dtype='<U21')

In [36]:
%%R
vectorR1=c(1,2,3,4,"o")
vectorR1

[1] "1" "2" "3" "4" "o"
